name: 'Package and Publish'
description: 'Publish actions as OCI artifacts to GHCR'

# TODO: Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    required: true
    description: >
      GITHUB_TOKEN having the write:package scope to publish an action package to GHCR.
    default: ${{ github.token }}
  path:
    required: false
    description: The work directory or path to be tar archived and uploaded as OCI Artifact layer.
    default: '.'
  registry:
    required: false
    description: The registry to publish the action package to.
    default: https://ghcr.io/ # TODO: this should perhaps be fetched from GitHub API.

outputs:
  package-url:
    description: 'The name of package published to GHCR along with semver. For example, https://ghcr.io/actions/package-action:1.0.1'
  package-manifest:
    description: 'The package manifest of the published package in JSON format'
runs:
  using: 'node16'
  main: 'dist/index.js'
