# Package and publish the action when a new release is published
# Since this is the publishing action itself, we can use the current checkout as the action
name: 'Publish Immutable Action Version'
on:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Publish Immutable Action Version
        uses: ./
