name: 'release'
on: # rebuild any PRs and main branch changes
  release:
    types: [created]
jobs:
  package-and-publish: 
    runs-on: ubuntu-latest
    steps:
      - name: Checking out!
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3.6.0
        with:
           node-version: 16
      - name: Publish action package
        uses: ./
